runtime: java11
entrypoint: java -Xmx64m -jar demo-0.3.jar
instance_class: F2
automatic_scaling:
  max_pending_latency: 30ms
  min_idle_instances: 2
  max_idle_instances: 10
handlers:
- url: /.*
  script: auto